# Generated by Django 3.2.9 on 2021-11-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, default='£', max_length=30, null=True)),
                ('limit', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
